apiVersion : apps/v1
kind: Deployment
metadata:
  name: "99990540"
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: "99990540"
          command: ["java","-jar","/app.jar"]
          args: ["--spring.config.location=file:/config/application.yml"]
          volumeMounts:
          - mountPath: /mnt/cloud-sample
            name: "vol-99990540"
            readOnly: false
            subPath: cloud-sample
          - mountPath: /config
            name: application-properties
            readOnly: true
                          
      volumes:
      - name: "vol-99990540"
        persistentVolumeClaim:
          claimName: cepg-aa-std-pvc
      - name: application-properties
        configMap:
          name: "99990540-configmap"
          items:
            - key: application.yml
              path: application.yml
          defaultMode: 420
